name: afterglow-data-clean
channels:
  - conda-forge
  - nodefaults
dependencies:
  - python=3.12
  - fastapi
  - joblib
  - lightgbm
  - numpy
  - pandas
  - pydantic>=2
  - scikit-learn
  - uvicorn
